{% set version = "0.4.2" %}

package:
  name: python-highcharts
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/p/python-highcharts/python-highcharts-{{ version }}.tar.gz
  sha256: c0f865f982da4c1d276f665f6633b30053b5bc4e8943d67b988379c3411d9d6b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - jinja2
    - future

test:
  imports:
    - highcharts
    - highcharts.highcharts
    - highcharts.highmaps
    - highcharts.highstock

about:
  home: https://github.com/kyper-data/python-highcharts
  license: MIT
  summary: 'Python Highcharts wrapper'

extra:
  recipe-maintainers:
    - mariusvniekerk
