{% set version = "0.4.1" %}
{% set name = "python-highcharts" %}
{% set sha256 = "da7965e54687ee9baa65119d8cc4cb170928e0fd1f56b0479bdc403c9fe7f866" %}

package:
  name: {{ name }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - jinja2
    - future

test:
  imports:
    - highcharts
    - highcharts.highcharts
    - highcharts.highmaps
    - highcharts.highstock

about:
  home: https://github.com/kyper-data/python-highcharts
  license: MIT
  summary: 'Python Highcharts wrapper'

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
