# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Xx+m7kIy5iFuj1W6GPd5/5gJflyp9bcmpLonHAUOi9CWQAyghZBbRUMWKrlqfotgaAXOvBbfEmidM2GsbTL46piT/PFKf5S4zYx6r6VOJCUamVmGScbtaFLPztfE8bMX5g5zQ4xftqe8LhL/foh629mr3YlWyNSZ1toiEjR1r0Nh6Khk8tbrfsZvSaMtSssu2dGGMeZwdstDBNN438qffoqRmvoUhPey9AmhWJz5R5asmeM8YzMZT4ixEe1Tryc+m9tE+uZpB0Fow3lSRKZkHH4iH7yl2ixdL55cyDAWST+oC/CQsSHIeOo63u5A8fiqGW+RefRb3AdQRGH0XX1pyH3vup1th1tkjRa/PlRZPuy65UmvnGg76ySQag0vnXjS6dXJpx/GUPfobKCzHJ8qXDfrMmTYlDkN/FehyW8Oqz87Vo2+OqxgRn9tnMswiO7d1IGx1bdxYfhA/B7py1Ks1RXLyO3BMiEnPhURcm/yFsHUPoJ3FFoUS5vdSOvnzM58eoJifD5vHhiTW/gOnsarmmY0DutmglPkmSzgv5c9bUBiTU0j6rZwbn2b9ac+z48cY5ElbCYwgRS/uIWwu7F0aGze9gqEzH705XQ4cCt5wb3uR9/FcTxmikwv/gTijSf2ASF0pkhDe+0ZJATL2bBLbiU8PyrgyG7nf6n+CfiC0BY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
