travis:
  secure:
    BINSTAR_TOKEN: XhPx3HHc8oejLTiw2tcoCZJTgSlcL8OVMbMGFsXG1/ErmHI6jyi8h6Oq0QNOD/2V40sPGSGTu7RqhOY10FA0jyZOy/Szog6JH9tQwceN3OjVUaXW50hj+YSCmms/DezVcSt/0/kaXv6nSZmjEgFHa06K/aZxPjJ8Um38SWeNPzv2I8s4QhZ2GqvBHcA7BkhcdWWjaMZjo2DyyGKFvUWZTj1FhbLJ+8WQxy917hAeNMwClNew9/8uoAQOrFxV+N5q5f4HAVNjIg/7WYtjqo6f1bkKVd9T5KWouq/oQWYw+0aUIBReYiOs9YSlnuDX3x6k0m/AyeRCmB9xSK7R4dkYr3K/6IlHuD7HeaWTkyGXYT/vGDu9+Wn7vwy0FnNhWLAaZEZ5NGVTsZaNgdfsONIZIKkJKqNKfrembhaZ4HqENPGHIAujMm6nbXrOS/CGlDdBYd9jdaFDenmTI5R8j8rTpJ6X7Dk7qANBRgeCE8TYfOb1bchAigervXIXT2mjBpKdOuEMESTNMH/xduZHqCrU6z+/darzjKWzGjAowZLBa5ax7fEbXzHBt9Rd/c6/gpnqtwT8wS7hMIWbJiFszU/sGDSmPiMDs/qjcWML/rnP/Z5vWIDGstx3BNH3QrMA0jCjjydmVOoavsWZOz3HLMN56CrCZUsRpMOmD8vts7o1pwo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
